In [14]:
import os
from dotenv import load_dotenv
from kaggle.api.kaggle_api_extended import KaggleApi
import pandas as pd

# Load environment variables
load_dotenv()

# Retrieve the Kaggle API credentials from environment variables
kaggle_username = os.getenv('KAGGLE_USERNAME')
kaggle_key = os.getenv('KAGGLE_KEY')

# Authenticate with Kaggle API
api = KaggleApi()
api.authenticate()

# Download the dataset
api.dataset_download_files('abcsds/pokemon', path='./pokemon_dataset', unzip=True)

# Load the dataset into a DataFrame
df = pd.read_csv('./pokemon_dataset/Pokemon.csv')

# Display the first few rows of the dataset
df.head()

Dataset URL: https://www.kaggle.com/datasets/abcsds/pokemon


#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [13]:
df0 = df

In [27]:
# NaN values
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [28]:
df.describe()

#      Total          HP      Attack     Defense     Sp. Atk  \
count  800.000000  800.00000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750  435.10250   69.258750   79.001250   73.842500   72.820000   
std    208.343798  119.96304   25.534669   32.457366   31.183501   32.722294   
min      1.000000  180.00000    1.000000    5.000000    5.000000   10.000000   
25%    184.750000  330.00000   50.000000   55.000000   50.000000   49.750000   
50%    364.500000  450.00000   65.000000   75.000000   70.000000   65.000000   
75%    539.250000  515.00000   80.000000  100.000000   90.000000   95.000000   
max    721.000000  780.00000  255.000000  190.000000  230.000000  194.000000   

          Sp. Def       Speed  Generation  
count  800.000000  800.000000   800.00000  
mean    71.902500   68.277500     3.32375  
std     27.828916   29.060474     1.66129  
min     20.000000    5.000000     1.00000  
25%     50.000000   45.000000     2.00000  
50%     70.000000   65.000000     3.00000  
75%     90.000000   90.000000     5.00000  
max    230.000000  180.000000     6.00000

In [83]:
strong = df[df['Total'] > 650]
strong.sort_values(by=['Total'])

#                     Name   Type 1    Type 2  Total   HP  Attack  \
710  646                   Kyurem   Dragon       Ice    660  125     130   
313  289                  Slaking   Normal       NaN    670  150     160   
423  383                  Groudon   Ground       NaN    670  100     150   
421  382                   Kyogre    Water       NaN    670  100     100   
543  486                Regigigas   Normal       NaN    670  110     160   
425  384                 Rayquaza   Dragon    Flying    680  105     150   
269  249                    Lugia  Psychic    Flying    680  106      90   
162  150                   Mewtwo  Psychic       NaN    680  106     110   
540  483                   Dialga    Steel    Dragon    680  100     120   
706  643                 Reshiram   Dragon      Fire    680  100     120   
707  644                   Zekrom   Dragon  Electric    680  100     150   
545  487     GiratinaOrigin Forme    Ghost    Dragon    680  150     120   
541  484                   Palkia    Water    Dragon    680   90     120   
544  487    GiratinaAltered Forme    Ghost    Dragon    680  150     100   
270  250                    Ho-oh     Fire    Flying    680  106     130   
793  717                  Yveltal     Dark    Flying    680  126     131   
792  716                  Xerneas    Fairy       NaN    680  126     131   
798  720       HoopaHoopa Unbound  Psychic      Dark    680   80     160   
494  445    GarchompMega Garchomp   Dragon    Ground    700  108     170   
268  248  TyranitarMega Tyranitar     Rock      Dark    700  100     164   
413  376  MetagrossMega Metagross    Steel   Psychic    700   80     145   
409  373  SalamenceMega Salamence   Dragon    Flying    700   95     145   
418  380        LatiasMega Latias   Dragon   Psychic    700   80     100   
711  646       KyuremBlack Kyurem   Dragon       Ice    700  125     170   
712  646       KyuremWhite Kyurem   Dragon       Ice    700  125     120   
796  719      DiancieMega Diancie     Rock     Fairy    700   50     160   
420  381        LatiosMega Latios   Dragon   Psychic    700   80     130   
552  493                   Arceus   Normal       NaN    720  120     120   
424  383    GroudonPrimal Groudon   Ground      Fire    770  100     180   
422  382      KyogrePrimal Kyogre    Water       NaN    770  100     150   
164  150      MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150   
163  150      MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190   
426  384    RayquazaMega Rayquaza   Dragon    Flying    780  105     180   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
710       90      130       90     95           5       True  
313      100       95       65    100           3      False  
423      140      100       90     90           3       True  
421       90      150      140     90           3       True  
543      110       80      110    100           4       True  
425       90      150       90     95           3       True  
269      130       90      154    110           2       True  
162       90      154       90    130           1       True  
540      120      150      100     90           4       True  
706      100      150      120     90           5       True  
707      120      120      100     90           5       True  
545      100      120      100     90           4       True  
541      100      150      120    100           4       True  
544      120      100      120     90           4       True  
270       90      110      154     90           2       True  
793       95      131       98     99           6       True  
792       95      131       98     99           6       True  
798       60      170      130     80           6       True  
494      115      120       95     92           4      False  
268      150       95      120     71           2      False  
413      150      105      110    110           3      False  
409      130      120       90    12

In [77]:
all = df[df['Legendary']==True][['Name', 'Total', 'Legendary']]
print(all.count())
print(all)

Name         65
Total        65
Legendary    65
dtype: int64
                    Name  Total  Legendary
156             Articuno    580       True
157               Zapdos    580       True
158              Moltres    580       True
162               Mewtwo    680       True
163  MewtwoMega Mewtwo X    780       True
..                   ...    ...        ...
795              Diancie    600       True
796  DiancieMega Diancie    700       True
797  HoopaHoopa Confined    600       True
798   HoopaHoopa Unbound    680       True
799            Volcanion    600       True

[65 rows x 3 columns]


In [29]:
# Convert 'Total', 'HP', 'Attack', 'Defense' columns to a NumPy array
stats_array = df[['Total', 'HP', 'Attack', 'Defense']].to_numpy()

# Display the shape and first few elements of the array
print(stats_array.shape)
print(stats_array[:5])


(800, 4)
[[318  45  49  49]
 [405  60  62  63]
 [525  80  82  83]
 [625  80 100 123]
 [309  39  52  43]]


In [31]:
high_stat_pokemon = stats_array[stats_array[:, 0] > 650]
high_stat_pokemon

array([[680, 106, 110,  90],
       [780, 106, 190, 100],
       [780, 106, 150,  70],
       [700, 100, 164, 150],
       [680, 106,  90, 130],
       [680, 106, 130,  90],
       [670, 150, 160, 100],
       [700,  95, 145, 130],
       [700,  80, 145, 150],
       [700,  80, 100, 120],
       [700,  80, 130, 100],
       [670, 100, 100,  90],
       [770, 100, 150,  90],
       [670, 100, 150, 140],
       [770, 100, 180, 160],
       [680, 105, 150,  90],
       [780, 105, 180, 100],
       [700, 108, 170, 115],
       [680, 100, 120, 120],
       [680,  90, 120, 100],
       [670, 110, 160, 110],
       [680, 150, 100, 120],
       [680, 150, 120, 100],
       [720, 120, 120, 120],
       [680, 100, 120, 100],
       [680, 100, 150, 120],
       [660, 125, 130,  90],
       [700, 125, 170, 100],
       [700, 125, 120,  90],
       [680, 126, 131,  95],
       [680, 126, 131,  95],
       [700,  50, 160, 110],
       [680,  80, 160,  60]])