# Numpy Basics



1. Numpy array
    - 1-dimensional array
    - Multidimensional array
    - Convert Python list to Numpy array
2. Slicing arrays
    - 1D array
    - 2D array
3. Numpy functions
    - Statistical functions
    - Transpose
    - Indexes of numpy array
    - Stacking arrays
    - Concatenate arrays
    - Copy and View
    - Universal functions

import numpy

In [3]:
import numpy as np

#### 1. Numpy array

##### 1-dimensional array

In [6]:
# Create 1-dimensional ndarray
np1d = np.array([1,2,3,4,5,6])
np1d

array([1, 2, 3, 4, 5, 6])

In [7]:
# check shape of the array
np1d.shape

(6,)

In [14]:
# 'arange' can be used to create array
np1d = np.arange(6)
np1d

array([0, 1, 2, 3, 4, 5])

In [15]:
# 'arange' contain 3 parameters: start value, end value, step)
np1d = np.arange(0, 60, 6)
np1d

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [104]:
# 'linspace' contain 3 parameters: start, end, number of elements
np1d = np.linspace(1, 6, 11)
np1d

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [16]:
# Create arrays with value 0
np1d = np.zeros(6)
np1d

array([0., 0., 0., 0., 0., 0.])

##### Multidimensional array

In [17]:
# 2-dimensional array
np2d = np.array([[1,2,3],[4,5,6]])
np2d

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
# 2-dimensional, all zeroes
np2d = np.zeros((3, 5))
np2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [117]:
# 'eye' defines a 2D identity matrix
np3d = np.eye(3, 5)
np3d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [112]:
# 3-dimensional array
np3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [119]:
np3d = np.ones((2, 3))
np3d

array([[1., 1., 1.],
       [1., 1., 1.]])

##### Convert Python list to Numpy array

In [30]:
# Create list with Python
list1 = [1,2,3,4,5,6]
list1

[1, 2, 3, 4, 5, 6]

In [31]:
# 1st item in the list
list1[0]

1

In [32]:
# covert previously created list1
print('Python list:', list1)
np1 = np.array(list1)
print('Numpy array:', np1)

Python list: [1, 2, 3, 4, 5, 6]
Numpy array: [1 2 3 4 5 6]


In [33]:
# print element in numpy array
print('Numpy array, 1st:', np1[0])

# Note the special case: index -1 points to last item 
print('Numpy array, last:', np1[-1])

Numpy array, 1st: 1
Numpy array, last: 6


### 2. Slicing arrays

#### 1D array

In [39]:
# Create 1-dimensional ndarray
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

# print slice
np1[1:6]

array([2, 3, 4, 5, 6])

In [35]:
# print all values starting from specific location
np1[5:]

array([ 6,  7,  8,  9, 10])

In [38]:
# print negative slices
np1[-5:-1]

array([6, 7, 8, 9])

In [37]:
# slices in steps
print(np1[1:6])
print(np1[1:6:2]) # some data in steps of 2
print(np1[::2]) # all data in steps of 2

[2 3 4 5 6]
[2 4 6]
[1 3 5 7 9]


#### 2D array

In [40]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
# print based on index in the array
#fist
print(np2[0,0])
print(np2[1,0])

#last
print(np2[0,-1])
print(np2[-1,-1])


1
6
5
10


In [45]:
# slice 2D array
# show in first row values in columns with indexes 1 - 3
print(np2[0:1,1:4])

[[2 3 4]]


In [46]:
# show data in row with index 1
# show the first row in the array
print(np2[0,:])

[1 2 3 4 5]


In [47]:
# Note that if all columns also option to print this way
print(np2[0,])

[1 2 3 4 5]


In [48]:
# show the last column in the array
print(np2[:,-1])

[ 5 10]


In [49]:
# show the previous result as array
a = np2[:, -1]
a

array([ 5, 10])

### 3. Numpy functions


#### Statistical functions


In [66]:
# array
print('array np1:', np1)

# print mean
print('mean:', np.mean(np1))

# print standard deviation, std
print('standard deviation:', np.std(np1))

# print median
print('median:', np.median(np1))

array np1: [ 1  2  3  4  5  6  7  8  9 10]
mean: 5.5
standard deviation: 2.8722813232690143
median: 5.5


#### Transpose

In [72]:
# before transpose np2
print('np2: \n', np2)

np2: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [73]:
# transpose np2
np2t = np.transpose(np2)
print('Transposed np2: \n',  np2t)

Transposed np2: 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


#### Indexes of numpy array

In [74]:
# Create 1-dimensional Numpy arrays with random values.
np3 = np.random.rand(10)
print ('np3: \n', np3)

np3: 
 [0.74094604 0.55813275 0.48194074 0.38111561 0.93675603 0.31984083
 0.49319887 0.78000339 0.71158284 0.64072761]


In [75]:
# find smallest and largest
np3min = np.argmin(np3)
np3max = np.argmax(np3)
print ('Index of smallest value is', np3min, 'with value:', np3[np3min])
print ('Index of largest value is', np3max, 'with value:', np3[np3max])

Index of smallest value is 5 with value: 0.3198408281444872
Index of largest value is 4 with value: 0.9367560273753129


#### Stacking arrays

In [80]:
# Create 2-dimensional Numpy arrays
np4 = np.array([1,2,3,4])
np5 = np.array([5,6,7,8])
print('np4:', np4)
print('np5:', np5)

np4: [1 2 3 4]
np5: [5 6 7 8]


In [81]:
# stack the arrays
np4_5 = np.stack((np4, np5))
print ('np4 and np5 stacked: \n', np4_5)

np4 and np5 stacked: 
 [[1 2 3 4]
 [5 6 7 8]]


In [82]:
# stack the arrays horizontally
np4_5h = np.hstack((np4, np5))
print ('np4 and np5 stacked horizontally: \n', np4_5h)

np4 and np5 stacked horizontally: 
 [1 2 3 4 5 6 7 8]


In [83]:
# Stack vertically same as stack
np4_5v = np.vstack((np4, np5))
print ('np4 and np5 stacked vertically: \n', np4_5v)

np4 and np5 stacked vertically: 
 [[1 2 3 4]
 [5 6 7 8]]


#### Concatenate arrays

In [84]:
# Create 2-dimensional Numpy arrays with random values.
np6 = np.random.rand(2,5)
print ('np6: \n', np6)
# Create 2-dimensional Numpy arrays with random values.
np7 = np.random.rand(2,5)
print ('np7: \n', np7)

np6: 
 [[0.91216426 0.56181645 0.67773607 0.26670934 0.38655873]
 [0.02625671 0.68179321 0.48557899 0.15354953 0.26885428]]
np7: 
 [[0.59257483 0.47724489 0.06616991 0.4585557  0.59745883]
 [0.06061358 0.34043176 0.81851215 0.18619035 0.15344223]]


In [123]:
# round
np6 = np.round(np6, 4)
np7 = np.round(np7, 2)
print(np6)
print(np7)

[[0.9122 0.5618 0.6777 0.2667 0.3866]
 [0.0263 0.6818 0.4856 0.1536 0.2688]]
[[0.59 0.48 0.07 0.46 0.6 ]
 [0.06 0.34 0.82 0.19 0.15]]


In [124]:
np.concatenate((np6, np7), axis=0)

array([[0.9122, 0.5618, 0.6777, 0.2667, 0.3866],
       [0.0263, 0.6818, 0.4856, 0.1536, 0.2688],
       [0.59  , 0.48  , 0.07  , 0.46  , 0.6   ],
       [0.06  , 0.34  , 0.82  , 0.19  , 0.15  ]])

In [125]:
np.concatenate((np6, np7), axis=1)

array([[0.9122, 0.5618, 0.6777, 0.2667, 0.3866, 0.59  , 0.48  , 0.07  ,
        0.46  , 0.6   ],
       [0.0263, 0.6818, 0.4856, 0.1536, 0.2688, 0.06  , 0.34  , 0.82  ,
        0.19  , 0.15  ]])

#### Copy and View

In [87]:
# create array with 'arange'
np8 = np.arange(0, 100, 5)
print(np8)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [88]:
# make a copy
np9 = np8.copy()
np9

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [89]:
# use view instead
np10 = np8.view()
np10

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [90]:
# change value in original array (np8)
np8[0] = 100
np8

array([100,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95])

In [91]:
# check values in the copy and view
print ('copy of np8: ', np9)
print ('view of np8: ', np10)

copy of np8:  [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
view of np8:  [100   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95]


#### Universal functions

In [92]:
# square root
print(np1)
print(np.sqrt(np1))

[ 1  2  3  4  5  6  7  8  9 10]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [93]:
# Absolute values  
np3 = np.array([-5,-3, -2, 0, 2, 5,7,9])
print(np.absolute(np3))

[5 3 2 0 2 5 7 9]


In [94]:
# Exponent
print(np.exp(np3))

[6.73794700e-03 4.97870684e-02 1.35335283e-01 1.00000000e+00
 7.38905610e+00 1.48413159e+02 1.09663316e+03 8.10308393e+03]


In [95]:
# min & max
print('min:', np.min(np3))
print('max:', np.max(np3))

min: -5
max: 9


numpy basics 1.0.1  
Henna