# Numpy Basics



1. Numpy array
    - 1-dimensional array
    - Multidimensional array
    - Convert Python list to Numpy array
2. Slicing arrays
    - 1D array
    - 2D array
3. Numpy functions
    - Statistical functions
    - Transpose
    - Indexes of numpy array
    - Stacking arrays
    - Concatenate arrays
    - Copy and View
    - Universal functions

import numpy

In [16]:
# pip install numpy

# imports
import numpy as np

#### 1. Numpy array

##### 1-dimensional array

In [19]:
# Create 1-dimensional ndarray
np1d = np.array([1,2,3,4,5,6])
print(np1d)

# check shape of the array
print(np1d.shape)

[1 2 3 4 5 6]
(6,)


In [20]:
# 'arange' can be used to create array
np1d = np.arange(6)
print('arange(6)\n', np1d)

# 'arange' contain 3 parameters: start value, end value, step)
np1d = np.arange(0, 60, 6)
print('\narange(0, 60, 6)\n', np1d)

arange(6)
 [0 1 2 3 4 5]

arange(0, 60, 6)
 [ 0  6 12 18 24 30 36 42 48 54]


In [21]:
# 'linspace' contain 3 parameters: start, end, number of elements
np1d = np.linspace(1, 6, 11)
np1d

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [22]:
# Create arrays with value 0
np1d = np.zeros(6)
np1d

array([0., 0., 0., 0., 0., 0.])

##### Multidimensional array

In [24]:
# 2-dimensional array
np2d = np.array([[1,2,3],[4,5,6]])
np2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# 2-dimensional, all zeroes
np2d = np.zeros((3, 5))
np2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
# 'eye' defines a 2D identity matrix
np3d = np.eye(3, 5)
np3d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [27]:
# 3-dimensional array
np3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
# 'ones' n, m
np3d = np.ones((2, 3))
np3d

array([[1., 1., 1.],
       [1., 1., 1.]])

##### Convert Python list to Numpy array

In [30]:
# Create list with Python
list1 = [1,2,3,4,5,6]
list1

[1, 2, 3, 4, 5, 6]

In [31]:
# 1st item in the list
list1[0]

1

In [32]:
# covert previously created list1
print('Python list:', list1)
np1 = np.array(list1)
print('Numpy array:', np1)

Python list: [1, 2, 3, 4, 5, 6]
Numpy array: [1 2 3 4 5 6]


In [33]:
# print element in numpy array
print('Numpy array, 1st:', np1[0])

# Note the special case: index -1 points to last item 
print('Numpy array, last:', np1[-1])

Numpy array, 1st: 1
Numpy array, last: 6


### 2. Slicing arrays

#### 1D array

In [36]:
# Create 1-dimensional ndarray
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np1)

# print slice
print('np1[1:6]:', np1[1:6])

# print all values starting from specific location
print('np1[5:]:', np1[5:])

# print negative slices
print('np1[-5:-1]:', np1[-5:-1])

[ 1  2  3  4  5  6  7  8  9 10]
np1[1:6]: [2 3 4 5 6]
np1[5:]: [ 6  7  8  9 10]
np1[-5:-1]: [6 7 8 9]


In [37]:
# slices in steps
print(np1[1:6])
print(np1[1:6:2]) # some data in steps of 2
print(np1[::2]) # all data in steps of 2

[2 3 4 5 6]
[2 4 6]
[1 3 5 7 9]


#### 2D array

In [39]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
# print based on index in the array
#fist
print(np2[0,0])

#last
print(np2[-1,-1])


1
10


In [41]:
# slice 2D array

# show in first row values in columns with indexes 1 - 3
print(np2[0:1,1:4])

# show data in row with index 1
# show the first row in the array
print(np2[0,:])

# Note that if all columns also option to print this way
print(np2[0,])

# show the last column in the array
print(np2[:,-1])

[[2 3 4]]
[1 2 3 4 5]
[1 2 3 4 5]
[ 5 10]


In [42]:
# show the previous result as array
a = np2[:, -1]
a

array([ 5, 10])

### 3. Numpy functions


#### Statistical functions


In [45]:
# array
print(np1)

# print mean
print('mean:', np.mean(np1))

# print standard deviation, std
print('standard deviation:', np.std(np1))

# print median
print('median:', np.median(np1))

[ 1  2  3  4  5  6  7  8  9 10]
mean: 5.5
standard deviation: 2.8722813232690143
median: 5.5


#### Transpose

In [47]:
# before transpose np2
print('np2: \n', np2)

np2: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [48]:
# transpose np2
np2t = np.transpose(np2)
print('Transposed np2: \n',  np2t)

Transposed np2: 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


#### Indexes of numpy array

In [50]:
# Create 1-dimensional Numpy arrays with random values.
np3 = np.random.rand(10)
print ('np3: \n', np3)

np3: 
 [0.76471044 0.43003775 0.34583297 0.87824215 0.30058113 0.04915601
 0.46858873 0.61519589 0.43568196 0.6441515 ]


In [51]:
# find smallest and largest
np3min = np.argmin(np3)
np3max = np.argmax(np3)
print ('Index of smallest value is', np3min, 'with value:', np3[np3min])
print ('Index of largest value is', np3max, 'with value:', np3[np3max])

Index of smallest value is 5 with value: 0.04915601450030138
Index of largest value is 3 with value: 0.8782421481511996


#### Stacking arrays

In [53]:
# Create 2-dimensional Numpy arrays
np4 = np.array([1,2,3,4])
np5 = np.array([5,6,7,8])
print('np4:', np4)
print('np5:', np5)

np4: [1 2 3 4]
np5: [5 6 7 8]


In [54]:
# stack the arrays
np4_5 = np.stack((np4, np5))
print ('np4 and np5 stacked: \n', np4_5)

np4 and np5 stacked: 
 [[1 2 3 4]
 [5 6 7 8]]


In [55]:
# stack the arrays horizontally
np4_5h = np.hstack((np4, np5))
print ('np4 and np5 stacked horizontally: \n', np4_5h)

# Stack vertically same as stack
np4_5v = np.vstack((np4, np5))
print ('\nnp4 and np5 stacked vertically: \n', np4_5v)

np4 and np5 stacked horizontally: 
 [1 2 3 4 5 6 7 8]

np4 and np5 stacked vertically: 
 [[1 2 3 4]
 [5 6 7 8]]


#### Concatenate arrays

In [57]:
# Create 2-dimensional Numpy arrays with random values.
np6 = np.random.rand(2,5)
print ('np6: \n', np6)
# Create 2-dimensional Numpy arrays with random values.
np7 = np.random.rand(2,5)
print ('np7: \n', np7)

np6: 
 [[0.54923657 0.9181361  0.34779538 0.59468906 0.54079941]
 [0.54528872 0.0989318  0.27224334 0.62006304 0.75111138]]
np7: 
 [[0.17767025 0.92377819 0.8533699  0.40217225 0.52779509]
 [0.95021681 0.86936803 0.62891666 0.81047093 0.60802125]]


In [58]:
# round
np6 = np.round(np6, 4)
np7 = np.round(np7, 2)
print(np6)
print(np7)

[[0.5492 0.9181 0.3478 0.5947 0.5408]
 [0.5453 0.0989 0.2722 0.6201 0.7511]]
[[0.18 0.92 0.85 0.4  0.53]
 [0.95 0.87 0.63 0.81 0.61]]


In [59]:
np.concatenate((np6, np7), axis=0)

array([[0.5492, 0.9181, 0.3478, 0.5947, 0.5408],
       [0.5453, 0.0989, 0.2722, 0.6201, 0.7511],
       [0.18  , 0.92  , 0.85  , 0.4   , 0.53  ],
       [0.95  , 0.87  , 0.63  , 0.81  , 0.61  ]])

In [60]:
np.concatenate((np6, np7), axis=1)

array([[0.5492, 0.9181, 0.3478, 0.5947, 0.5408, 0.18  , 0.92  , 0.85  ,
        0.4   , 0.53  ],
       [0.5453, 0.0989, 0.2722, 0.6201, 0.7511, 0.95  , 0.87  , 0.63  ,
        0.81  , 0.61  ]])

#### Copy and View

In [62]:
# create array with 'arange'
np8 = np.arange(0, 100, 5)
print(np8)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [63]:
# make a copy
np9 = np8.copy()
np9

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [64]:
# use view instead
np10 = np8.view()
np10

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [65]:
# change value in original array (np8)
np8[0] = 100
np8

array([100,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95])

In [66]:
# check values in the copy and view
print ('copy of np8: ', np9)
print ('view of np8: ', np10)

copy of np8:  [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
view of np8:  [100   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95]


#### Universal functions

In [68]:
# square root
print(np1)
print(np.sqrt(np1))

[ 1  2  3  4  5  6  7  8  9 10]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [69]:
# Absolute values  
np3 = np.array([-5,-3, -2, 0, 2, 5,7,9])
print(np.absolute(np3))

[5 3 2 0 2 5 7 9]


In [70]:
# Exponent
print(np.exp(np3))

[6.73794700e-03 4.97870684e-02 1.35335283e-01 1.00000000e+00
 7.38905610e+00 1.48413159e+02 1.09663316e+03 8.10308393e+03]


In [71]:
# min & max
print('min:', np.min(np3))
print('max:', np.max(np3))

min: -5
max: 9


numpy basics 1    
Henna 